#!/bin/sh

# Copyright (c) 2007-2008 Michael Schoonmaker <michael.r.schoonmaker@gmail.com>
# Copyright (c) 2007-2008 Michael Dippery <mpd@cs.wm.edu>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# Contributors:
#   Michael Dippery <mpd@cs.wm.edu>


if [ `uname -s` = "Darwin" ]; then
    xdock="-Xdock:name=Snodes"
fi

if [ "$SNODES_HOME" = "" ]; then
    if [ -e ./Snodes.jar ]; then
        snodes_path=./Snodes.jar
        snodes_cp='-cp ./lib/java-getopt-1.0.13.jar'
    else
        snodes_path=/usr/local/share/snodes/Snodes.jar
    fi
else
    snodes_path=$SNODES_HOME/Snodes.jar
fi

if [ -e $snodes_path ]; then
    java_cmd="java $snodes_cp -jar $xdock $snodes_path $*"
#    echo $java_cmd
    exec $java_cmd
else
    echo "Path not found: $snodes_path"
    exit 1
fi
