#!/bin/sh

# Copyright (c) 2007-2008 Michael Schoonmaker <michael.r.schoonmaker@gmail.com>
# Copyright (c) 2007-2008 Michael Dippery <mdippery@bucknell.edu>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# Contributors:
#   Michael Dippery <mdippery@bucknell.edu>


getopt_jar=java-getopt-1.0.13.jar

if [ `uname -s` = "Darwin" ]; then
    xdock="-Xdock:name=Snodes"
fi

if [ "$SNODES_HOME" = "" ]; then
    if [ -e ./Snodes.jar ]; then
        SNODES_PATH=Snodes.jar
        SNODES_CP=lib/$getopt_jar
    else
        SNODES_PATH=/usr/local/share/snodes/Snodes.jar
        SNODES_CP=/usr/local/share/snodes/lib/$getopt_jar
    fi
else
    SNODES_PATH=$SNODES_HOME/Snodes.jar
    SNODES_CP=$SNODES_HOME/lib/$getopt_jar
fi

if [ -e $SNODES_PATH ]; then
    exec java -cp $SNODES_CP -jar $xdock $SNODES_PATH $*
else
    echo "Path not found: $SNODES_PATH"
    exit 1
fi
